### ISSUE TITLE
Toggle diffview tab

### ISSUE THREAD

**Issue by LintaoAmons** [sindrets/diffview.nvim#418] opened 2023-09-15 09:34 UTC
Currently I can trigger multiple tab for diffview and I need to close the tab to close the diffview.

So if it's possible to have one action to just toggle diffview tab.

- new a diffview tab
- jump to diffview tab when there is existing one.
- close diffview tab if currently at diffview tab

**Comment by sindrets** [comment] 2023-09-17 09:46
Duplicate of #11.

Rel. #162

**Closed by sindrets** 2023-09-17 09:46 UTC
