### ISSUE TITLE
[feature/scope?] stage hunks

### ISSUE THREAD

**Issue by dkuettel** [sindrets/diffview.nvim#191] opened 2022-08-19 23:04 UTC
Hi,

I'm not sure if this is the intention of the plugin. Maybe also it's possible already and I cant find out how: Seeing as it shows me a diff between the working tree and the index, I expected that I could `dp` and `dg` just like in a normal diffview and this way stage hunks. Like in the fugitive plugin. Is the view I get in `DiffviewOpen` not a normal vim diff view? Is the intention of the tool to only view diffs, or also stage stuff?

cheers, Daniel.

**Comment by sindrets** [comment] 2022-08-20 11:00
Duplicate of #8 and #31.

> I expected that I could dp and dg just like in a normal diffview and this way stage hunks. Like in the fugitive plugin. Is the view I get in DiffviewOpen not a normal vim diff view?

I assume you meant `do` and not `dg`. Both `dp` and `do` work if the target buffer is a local file (that is the right side of the diff when you're comparing against the index). This plugin is indeed using the builtin `:h diff-mode`, and as such all features documented there should work.

Staging hunks by changing the index side of the diff is a Fugitive thing, not a builtin diff-mode thing, and as such that workflow does not work in this plugin. Please see my explanation in the linked issues for as to why I don't wish to implement hunk staging in this plugin.

Closing this as a duplicate, but let me know if you have any more questions.

**Closed by sindrets** 2022-08-20 11:00 UTC
