### ISSUE TITLE
Feature request. DiffviewToggle

### ISSUE THREAD

**Issue by invalidcpp** [sindrets/diffview.nvim#243] opened 2022-11-10 02:55 UTC
First off. Love this plugin. I'm new to neovim, and it's making the transition from VSCode to it, a lot easier and smoother.

I've already added this command to my local, but very janky. The idea is to just have a `DiffviewToggle` command, that either opens, or closes the view. My implementation doesn't allow for the DiffviewOpen options, so maybe this could be an improvement made.

Like I said the way I implemented it was very janky(I'm very new to lua), I just copied to DiffviewOpen command in [This file](https://github.com/sindrets/diffview.nvim/blob/main/plugin/diffview.lua) and added a `local toggle = 0` variable. if its `0` open the view, and set the toggle to `1`, else close it and set the toggle to `0` again. There is probably 100 better ways to implement this.

I did try to look to see if toggling was already available, but I couldn't see anything. If I missed it, apologies.

I find it a very useful command as now I can just bind one shortcut to it.

Thanks again for the helpful plugin!

**Comment by sindrets** [comment] 2022-11-10 16:55
Glad to hear you find the plugin useful!

I'm closing this as a duplicate of #188 and #11. Please see my explanations there for as to why I believe a toggle command is not a good fit.

I recommend that you get used to managing tab pages in vim. Nvim provides a default mapping `g<Tab>` to bring you back to your last accessed tab page. That functionally works as a toggle if you want to go back and fourth between two tab pages.

**Closed by sindrets** 2022-11-10 16:55 UTC
