### ISSUE TITLE
Error while loading lua module diffview.bootstrap

### ISSUE THREAD

**Issue by asmodeus812** [sindrets/diffview.nvim#145] opened 2022-05-31 04:05 UTC
Hi, i noticed that since i pulled the latest master there seems to be a problem within diffview. Seem like the latest patch from yesterday might have broken something 
![image](https://user-images.githubusercontent.com/15955811/171090664-4cf630bf-624d-477c-a653-34f43575f6f0.png)

**Comment by ecuyle** [comment] 2022-05-31 05:14
I'm also seeing this

**Comment by sindrets** [comment] 2022-05-31 09:11
I assume this is what we are already tracking in #144? You guys are using impatient.nvim?

**Comment by asmodeus812** [comment] 2022-05-31 10:21
Yep i do use it. Havent had this issue before though i have been using impatient all that time. I assumed its something with the latest commit

**Comment by sindrets** [comment] 2022-05-31 10:28
@asmodeus812 You're right that it didn't happen before. However, it's a compatibility issue, not a bug in diffview. Please check the other issue. I'm explaining the problem there, and I provided a temporary patch for impatient. I'm gonna try to create a PR later today.

Closing this, so that we can track it in 144.

**Closed by sindrets** 2022-05-31 10:28 UTC

**Comment by asmodeus812** [comment] 2022-05-31 16:26
@sindrets I am not 100% sure if it is the same problem since the error in 144 is very different from what i am seeing, can you elaborate ? Should we disable impatient (i saw you suggested modifying it) to make diffview require correctly ?

**Comment by sindrets** [comment] 2022-05-31 16:53
> loop or previous error loading module [...]

@asmodeus812 this means that there's at least one more error that is not visible in your screenshot. You can see these by running `:messages`. Without seeing the full error message it's hard to be certain, but I'm almost certain this is the same issue as 144. Especially if it was fixed by e5b47ebe620c1756fecb126845a941a75c78e9aa. Also when I was testing locally, I was seeing the same message that you show in your screenshot.

So to elaborate on the issue: it was only impatient's profiling module that was causing problems. Impatient overrides some of the internal module loading mechanisms, and I was using these in a somewhat unconventional way in order to check for the existence of the plugin's dependencies without actually loading them. And this was causing impatient's profiling to stumble.
