### ISSUE TITLE
Diffview only for selection related history

### ISSUE THREAD

**Issue by LintaoAmons** [sindrets/diffview.nvim#225] opened 2022-09-24 14:10 UTC
IDEA provide a function that show only the commits that related to the selected lines

It's kind like `DiffviewFileHistory %`, but filter out the unrelated commits.

Maybe this could be included into `Diffview`?

![history of selection](https://user-images.githubusercontent.com/95092244/192102548-d5465336-8386-4e0b-9544-348183767eb4.gif)

**Comment by sindrets** [comment] 2022-09-24 14:29
Duplicate of #187.

This feature already exists, and it's documented in both the README, and the docs.

**Closed by sindrets** 2022-09-24 14:29 UTC
