### ISSUE TITLE
[Question] File history panel

### ISSUE THREAD

**Issue by asmodeus812** [sindrets/diffview.nvim#140] opened 2022-05-26 12:48 UTC
Hi, while looking through the capabilities of this great plugin, i was initially not sure waht file history panel is. First i thought it was basically a git log. But when i went through the docs i realized it isnt really.  It has its uses no doubt, but the file history panel ui is incredibly nice and cool and i was wondering if it could be made to work like git log (head) for example. To show the list of commits for the selected revision/branch and be able to expand each commit to see what was introduced in that specific commit.

**Comment by sindrets** [comment] 2022-05-26 16:22
Yes, it *is* a git-log porcelain and you can use it that way! Although it might not be immediately apparent, because by default it targets your current file on HEAD. However, as you might have noticed it does accept path args, and if you provide the path to the top-level of the repo you will get the full list of changed files for each commit. And as it's relatively common to have your working directory being the top-level of the worktree, you can usually just pass `.` as the path arg:

```vim
:DiffviewFileHistory .
" This is the equivalent of `git log HEAD .`
```

You can also use the `--range` flag to specify a git rev other than HEAD:

```
:DiffviewFileHistory . --range=feat/foo-bar-baz
:DiffviewFileHistory . --range=HEAD~50..HEAD
:DiffviewFileHistory . --range=feat/lorem-ipsum...origin/main
```

**Comment by sindrets** [comment] 2022-05-31 16:54
@asmodeus812 Did this answer your question?

**Comment by asmodeus812** [comment] 2022-05-31 17:37
@sindrets Yes, in a way, indeed it works similarly to what git log does, but not exactly 1:1 output. I don't intend on using it as of now for that. I can't really explain it but diffview files shows "more commits", sometimes the same commit message but with different commit key/id . Also i am seeing commits which do not seem to exist (at least for the current branch) maybe it is aggregating from all branches, not sure.

**Comment by sindrets** [comment] 2022-05-31 20:22
> it works similarly to what git log does, but not exactly 1:1 output

@asmodeus812 Actually it *is* 1:1, because the plugin is literally parsing
git-log output. I'm guessing the reason you're thrown off if perhaps due to the
default options that the plugin passes to git-log, or maybe you're not familiar
with how git-log treats paths?

By default, the plugin uses the flags `--diff-merges=on --diff-merges=combined`.
This filters out merge commits that didn't actually change any files in the
given paths.

> diffview files shows "more commits", sometimes the same commit message but
> with different commit key/id

More than what? Git-log lists all the commits that affected the given paths,
regardless of branch. What you're describing as the "same commits with different
SHA" are probably merge commits. Both the commit from the merging branch, and
the resulting commit in the branch it was merged into.

> Also i am seeing commits which do not seem to exist (at least for the current
> branch) maybe it is aggregating from all branches, not sure.

Am I understanding you correctly, that you think git sees commits as "belonging
to" branches? If so, this is not the case. And I can promise you that the
commits you are seeing do exist. You can try running 
`:DiffviewFileHistory some/example/path` and comparing it to the output in your
shell when running:

```sh
git log --oneline -m -c -- some/example/path
# -m, -c are the shorthands for --diff-merges=on and --diff-merges=combined
```

The listed commits should be almost the same. The plugin only filters out
commits if they don't have any changes for the given paths.

Do note that you can already change some of the options passed to git-log by
pressing `g!` in the file history panel. I'm also very willing to add more
log options, so do let me know if you're missing any. `-L<start>,<end>` to see
history for a given line range is already planned.

**Comment by asmodeus812** [comment] 2022-06-01 03:34
Maybe there was a misunderstanding, in what i was going for here. So what i mean by log is the following (or at least the way i use it on the cli)
`git log --oneline --.` or `git log` or `git log --oneline`. Here is a sample output, that just lists the commits (without the merge ones, in that case but its not relevant for the discussion)
![image](https://user-images.githubusercontent.com/15955811/171322339-c8f25fec-6f9a-4960-8584-2041d4f7cbc1.png)

And below is what i see when i run `DiffviewFileHistory  .`
![image](https://user-images.githubusercontent.com/15955811/171322535-44a489f3-6bbf-4950-9ac7-be9f8633a26d.png)

**Comment by sindrets** [comment] 2022-06-01 12:02
Okay, now I think we're getting somewhere. So, what you would like, is to be
able to disable the default options passed to git-log, such that the listed
commits in the file history panel are equivalent to that which you get when you
run `git log` with no options on the cli?

> what i was initially curious is can diff file panel act like Telescope
> git_commits, but maybe it is no intended to by design

Sure that should also be possible. The intended design is for it to be a
slightly opinionated porcelain for git log, with focus on viewing diffs for each
revision. And the "slightly opinionated" part is why I add some default options
that I personally think are useful. But I would like the view to be more
configurable, and I intend to expose more options.

**Closed** 2022-06-01 14:31 UTC
Labels: question

**Comment by sindrets** [comment] 2022-06-07 19:21
@asmodeus812 In the latest commit (1a94f9908b39d43c25e5637b9e9afa7d134502c4) I have now made all the
git-log options configurable, and set better defaults. Further, calling
`:DiffviewFileHistory` with no path args is now the equivalent of calling
git-log with no path args. Please give this a try and see if the listed commits
are what you would expect. In my testing the listed commits in the file history
view with the default options are now identical to the output you get by
running `git log --oneline`.

If merge commits are not listed the way you would expect, try to adjust the
`--diff-merges` option, which has now been exposed in the option panel (`g!`).
This option determines how git-log treats merge commits, and it's willingness to
show stats for said commits.

**Comment by asmodeus812** [comment] 2022-06-08 18:37
Thanks, great update indeed, i just got around playing with it. Not sure what i am doing wrong, but below are examples of the same commit from the logs, diffed in neogit, intellij git (with delta) and diffview. Now the way those show the diff are like that `git diff  commit~..commit` as far as i know - i think the idea is showing the diff between the selected commit and the one immediately before it. Diffview does how some diff but i am not sure against what it compares that commit to generate the diff. (Does not seem to be head or index)
Neogit, Intellij and git + delta
![image](https://user-images.githubusercontent.com/15955811/172689670-c664440b-1b9c-4260-
bc7f-a55cd5db8e2c.png)

![image](https://user-images.githubusercontent.com/15955811/172690021-dfa1d3b7-a61b-49d1-b36d-5c70e87a1a99.png)

![image](https://user-images.githubusercontent.com/15955811/172690607-540b0d15-58ac-4052-aeb5-d1c6dd48d6d0.png)

![image](https://user-images.githubusercontent.com/15955811/172689972-f38bcd2f-7872-4c24-8ef2-d531d1b7e05e.png)

Diffview
![image](https://user-images.githubusercontent.com/15955811/172689858-299bc599-e4e0-4192-83b2-b8445daf11ac.png)
![image](https://user-images.githubusercontent.com/15955811/172689907-c6c3be8d-6840-4f91-8ec1-595b22bd6bd2.png)

```Lua
file_history_panel = {
        log_options = {
            single_file = {
                diff_merges = false,
            },
            multi_file = {
                diff_merges = false,
            }
        }
    },
```
Note the reason i have diff_merges set to false, is that  i was unable to make it display anything with any other option - such as "on" "off" or the default. (Diffview reports and info message that no results were found or something to that effect)

**Comment by sindrets** [comment] 2022-06-08 19:56
@asmodeus812 The file history view diffs the commits against the first commit parent. Which is what intellij does as well through it's git-log interface. I don't really know what to make of these screenshots. I can't tell what commit is being diffed against what other commit, and I don't know how you produced these diffs: did you do `git log -u`? Did you do `git diff {SOME COMMIT}`? In intellij, are what are you comparing against? The local changes?

If you *want* to compare history against a specific rev, then you can du that in this plugin with the `--base={git rev}` option.

> Note the reason i have diff_merges set to false, is that i was unable to make it display anything with any other option - such as "on" "off" or the default. (Diffview reports ad info message that no results were found or something to that effect)

Hm, this sounds strange. It would be great if you could provide either a tarball with a git repo that demonstrates this behavior (doesn't need to be real code, just a mock repo), or try to repoduce this behavior in a public repo so that it's possible for me to reproduce locally and debug.

> PS: Wanted to say how much i liked the detailed docs on the new changes

I'm glad to hear people appreciate this! I spend a fair amount of time trying to communicate changes clearly.

**Comment by asmodeus812** [comment] 2022-06-09 04:16
For the intellij diff, what i did is simply open the log panel, selected a commit, then the file, changed in that commit. When intellij popup opens the diff shows on the right the file from the current commit and on the left it shows the file in the immediate previous commit, (that is what i meant by diffing like that git diff commit~..commit). Here is an example of the hashes, the 04d... is the commit i open from the logs, and the 802.... commit is the one before it. What i used locally to demonstrate above (with git delta) was exactly that git diff [commit~]..[commit]. Just to verify that this is what i am seeing in both intellj and neogit.
![image](https://user-images.githubusercontent.com/15955811/172762637-621df29e-c048-4753-9e6f-569ee4347c93.png)

**Comment by sindrets** [comment] 2022-06-09 14:00
@asmodeus812 I understand that intuitively you might think it works this way, but you're making some wrong assumptions. `commit~` is not necessarily the commit that appears chronologically immediately before `commit` in the history. It will only appear that way with simple git history without real merges. Let me use an example from the Neovim git repo:

![image](https://user-images.githubusercontent.com/2786478/172860141-c3c8d03f-d07e-4ada-9a05-e439ef1f9aa9.png)

The log you're seeing is produced from `git log --oneline --graph master`. As you can see on the graph, and the rev-parse, `c632f64e2`'s parent commit is *not* it's immediate ancestor in the log history. And intellij knows this as well:

![image](https://user-images.githubusercontent.com/2786478/172861508-eb6b0d5a-77a8-4efb-931d-6ef5c524fc98.png)

<sup>Note it's comparing "Changes to e6652821 [...]"</sup>

On the other hand, this plugin should be showing the diff between `commit~..commit` as you put it, as this means "the range of revs between `commit` and its first parent". You can see what commit diffview has created the buffer from by looking at the full file name (press `<C-g>` to echo the full file name of the current buffer). The commit SHA will be after `.git/` in the path.

But I would like to get back to the fact that you're seemingly unable to list merge commits at all? Is it like this in all git repos for you? This sounds like it might be a bug. I would like to ask you again to please provide either a git rev in a public repo that I can clone, or a tarball with a repo that demonstrates this behavior.

**Comment by sindrets** [comment] 2022-06-15 16:58
@asmodeus812 I just found out that the `--diff-merges` option was added in git 2.31.0. I suspect you're using an older version of git. Try to update to a more recent version.
