### ISSUE TITLE
Error is thrown when restore action is used on an untracked file

### ISSUE THREAD

**Issue by steliyan** [sindrets/diffview.nvim#146] opened 2022-06-01 10:24 UTC
Maybe a concise warning can be shown or the file can be deleted (with or without a confirmation).

Error:
```
E5108: Error executing lua: ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: .../share/nvim/plugged/diffview.nvim/lua/diffview/utils.lua:262: bad argument #1 to 'concat'
(table expected, got string)
stack traceback:
        [C]: in function 'error'
        ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
        ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
        ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
        ...re/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:113: in function 'callback'
        ...share/nvim/plugged/diffview.nvim/lua/diffview/events.lua:46: in function 'call'
        ...share/nvim/plugged/diffview.nvim/lua/diffview/events.lua:149: in function 'emit'
        ....local/share/nvim/plugged/diffview.nvim/lua/diffview.lua:242: in function 'emit'
        ...hare/nvim/plugged/diffview.nvim/lua/diffview/actions.lua:182: in function <...hare/nvim/plugged/diffview.nvim/lua/diffview/actions.lua:181>
Press ENTER or type command to continue
```

**Comment by sindrets** [comment] 2022-06-01 10:29
I think you're on an outdated commit. This should have been fixed in 810948aae6f643929525c5f785e5cce18df113c8. It was a regression in one of the job utils. "Restoring" untracked files has been supported since 5871b5c70a4f2c73b1c972e227976e18d49ec087.

**Closed** 2022-06-02 12:45 UTC
