### ISSUE TITLE
Current file on left sometimes loses sync

### ISSUE THREAD

**Issue by sevensidedmarble** [sindrets/diffview.nvim#44] opened 2021-07-17 15:02 UTC
First off, wow, this plugin is tremendous. Great job.

One nitpick for me though is that when I tab through changed files, the highlighted file in the file list doesn't change to update which one I'm currently on.

EDIT: I just noticed it does work for me sometimes, so I wonder if there's a state or interaction that causes it to lose sync? Can anyone else confirm they've ever experienced this?

**Comment by sindrets** [comment] 2021-07-17 17:32
I haven't seen this before. It might be a bug or it might be related to your setup. It shouldn't be able to become out of sync, as I'm calculating the next cursor position each time I'm moving it. 

Can you give me a reproducible scenario with a minimal config?

**Comment by sindrets** [comment] 2021-08-02 19:10
Closing due to inactivity from OP.

**Closed by sindrets** 2021-08-02 19:10 UTC

**Comment by tom-anders** [comment] 2021-08-31 06:31
@sindrets I also have the same issue and can somewhat reproduce it. When I just do `DiffviewOpen`, everything works fine. But when I do `DiffviewOpen HEAD~1..HEAD` then it works until I reach the end of the file list, at which point jumping to the next file still works (wraps around to the beginning), but the file list is not updated anymore. Looks like having the second argument somehow messes things up? Hope this helps you to reproduce the issue.

**Comment by sindrets** [comment] 2021-08-31 13:47
@tom-anders I still can't reproduce it with the method you described. And without a minimal config it could be anything. If you can give me a minimal config where this is reproducible, I will gladly investigate this further.

**Comment by tom-anders** [comment] 2022-05-23 08:47
Can't reproduce anymore on HEAD either

**Comment by sindrets** [comment] 2022-05-23 16:16
@tom-anders Great to hear that! This was probably fixed by d928f07976bf50bf6fe963971bd0b1345e2d759d. It seems like cursorline highlights don't always update properly if the buffer's parent window is not focused when the cursor moves. This might be an upstream bug, I'm not sure.
