### ISSUE TITLE
[Question] Is there a shortcut to commit the staged changes?

### ISSUE THREAD

**Issue by LintaoAmons** [sindrets/diffview.nvim#142] opened 2022-05-28 04:20 UTC
After I use `diffview` to stage all the changes that I have made, I found it seems like have no commit action builtin into the plugin?

Or I just didn't notice it?

**Comment by sindrets** [comment] 2022-05-28 09:30
Duplicate of #57.

See my response there.

**Closed by sindrets** 2022-05-28 09:30 UTC
Labels: duplicate
