### ISSUE TITLE
Moving and Operating to next or previous diff

### ISSUE THREAD

**Issue by asmodeus812** [sindrets/diffview.nvim#131] opened 2022-05-01 08:05 UTC
Hi, Just wanted to first mention how nice this plugin is and how helpful. I was wondering if you have considered adding the ability to move change by change, possibly across files. I.e go to next change will first exhaust the changes in the current file and then move to the next in the list.
Another kind of related one is the ability to revert specific changes instead of the entire file ? I am not sure if that is already possible with  the out-of-the-box features.

**Comment by sindrets** [comment] 2022-05-01 16:22
Duplicate of #111.

> Hi, Just wanted to first mention how nice this plugin is and how helpful.

Glad to hear that!

> Another kind of related one is the ability to revert specific changes instead of the entire file ? I am not sure if that is already possible with the out-of-the-box features.

Sure, if the right side of the diff is showing the local state of the file just put your cursor over the diff hunk you want to revert and press `do`. This is also a built-in vim feature and is documented under `:h copy-diffs`.

If you want hunk staging: that is not implemented here, because this plugin does not operate on hunks and it's already implemented well in other plugins. I recommend [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim). Gitsigns provides features like hunk staging and much more, and it works in diffviews as well.

Closing this issue because your main question is answered in 111. Let me know if you have any other questions.

**Closed by sindrets** 2022-05-01 16:22 UTC

**Comment by asmodeus812** [comment] 2022-05-02 04:33
Great, thanks, do and dp work great, i was not aware of those. One additional question, is it possible to directly focus the current file when you open it from diff view or the history view. As of now when you select_entry the focus sits on the tree instead.

**Comment by barsv** [comment] 2022-08-25 18:28
> This is documented under `:h diffview-config-focus_entry`.

typo. It's documented under `:h diffview-actions-focus_entry`
