### ISSUE TITLE
Error on startup: invalid key: underdashed

### ISSUE THREAD

**Issue by TamaMcGlinn** [sindrets/diffview.nvim#214] opened 2022-09-15 19:13 UTC
Hi. After a recent update, I am faced with this error on startup:

```
Error detected while processing /home/tama/vimrc/diffview.vim:
line  126:
E5108: Error executing lua /home/tama/.vim/plugged/diffview.nvim/lua/diffview/hl.lua:264: invalid key: underdashed
stack traceback:
        [C]: in function 'nvim_set_hl'
        /home/tama/.vim/plugged/diffview.nvim/lua/diffview/hl.lua:264: in function 'hi'
        /home/tama/.vim/plugged/diffview.nvim/lua/diffview/hl.lua:432: in function 'update_diff_hl'
        /home/tama/.vim/plugged/diffview.nvim/lua/diffview/hl.lua:437: in function 'setup'
        /home/tama/.vim/plugged/diffview.nvim/lua/diffview/init.lua:78: in function 'init'
        /home/tama/.vim/plugged/diffview.nvim/lua/diffview/init.lua:410: in main chunk
        [C]: in function 'require'
        [string ":lua"]:5: in main chunk
```

**Comment by sindrets** [comment] 2022-09-15 19:18
Duplicate of #192.

Please see the solution I provided there.

**Closed by sindrets** 2022-09-15 19:18 UTC
