### ISSUE TITLE
[question] how do i change the empty space char?

### ISSUE THREAD

**Issue by alexzanderr** [sindrets/diffview.nvim#77] opened 2021-09-21 14:18 UTC
![image](https://user-images.githubusercontent.com/54772464/134188080-ac012fbf-3952-4a46-9bd0-2769658dc2b1.png)
i see that you have for empty space a `/` (slash char), unicode i guess.
mine is a simple `-`
![image](https://user-images.githubusercontent.com/54772464/134188264-d46256e4-c721-422a-ad11-837aac2b2c48.png)

how do i change that char?

**Comment by sindrets** [comment] 2021-09-21 15:02
Duplicate of #35. See my answer there. It is unicode, but it's going to depend on your terminal how well it looks. Kitty replaces all the full line / box drawing chars with its own to make them always look nice regardless of line height, column width, etc.

**Closed by sindrets** 2021-09-21 15:02 UTC

**Comment by bew** [comment] 2021-09-21 15:04
Check `:h 'fillchars'`, look for `diff:`
